---
# Grafana default variables
grafana_version: "11.3.1"
grafana_port: 3001
grafana_admin_user: admin
grafana_admin_password: admin123!
grafana_data_dir: /var/lib/grafana
grafana_log_dir: /var/log/grafana
grafana_plugins: []
